using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using DevExpress.Data;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Columns;

namespace OrderExport
{
    public partial class Form1 : RibbonForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource asynchronously
            //excelDataSource1.FillAsync();
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var fileContent = string.Empty;
            var filePath = string.Empty;

            using (var openFileDialog = new OpenFileDialog())
            {
                openFileDialog.Filter = "All files (*.*)|*.*";
                openFileDialog.FilterIndex = 2;
                openFileDialog.RestoreDirectory = true;

                if (openFileDialog.ShowDialog() == DialogResult.OK)
                {
                    filePath = openFileDialog.FileName;

                    excelDataSource1.FileName = openFileDialog.FileName;
                    excelDataSource1.Fill();

                }
            }
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            if (ConfirmDelete() == DialogResult.OK)
            {
                excelDataSource1.FileName = "";
                excelDataSource1.Fill(new List<IParameter>());
            }
        }

        private void gridControl_MouseHover(object sender, EventArgs e)
        {
            Console.WriteLine(sender);
        }


        /// <summary>
        /// 确认删除对话框
        /// </summary>
        /// /// <returns>用户点击结果</returns>
        public DialogResult ConfirmDelete()
        {
            return DevExpress.XtraEditors.XtraMessageBox.Show(
                "确定要删除吗？",
                "提示",
                MessageBoxButtons.OKCancel,
                MessageBoxIcon.Question);
        }
    }
}
