using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DevExpress.Data;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid.Columns;

namespace OrderExport
{
    public partial class Form1 : RibbonForm
    {
        public Form1()
        {
            InitializeComponent();

            // add checkboxes
            // var col_chkbox = new Gridcolumnch();
            //
            // col_chkbox.HeaderText = "X";
            // col_chkbox.Name = "checked";
            // col_chkbox.CellTemplate = new DataGridViewCheckboxCellFilter();
            //
            // this.gridView.Columns.Insert(0, col_chkbox);


            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource asynchronously
            excelDataSource1.FillAsync();
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var fileContent = string.Empty;
            var filePath = string.Empty;

            using (var openFileDialog = new OpenFileDialog())
            {
                openFileDialog.Filter = "All files (*.*)|*.*";
                openFileDialog.FilterIndex = 2;
                openFileDialog.RestoreDirectory = true;

                if (openFileDialog.ShowDialog() == DialogResult.OK)
                {
                    //Get the path of specified file
                    filePath = openFileDialog.FileName;

                    // var textEdit = new RepositoryItemImageEdit();
                    // textEdit.ContextImageOptions.Image = Image.FromFile("1.bmp");
                    // this.col图片.ColumnEdit = textEdit;
                    // this.gridControl.RepositoryItems.Add(textEdit);

                    excelDataSource1.FileName = openFileDialog.FileName;
                    excelDataSource1.Fill();

                }
            }
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.excelDataSource1.Fill(new List<IParameter>());
        }

        private void gridControl_MouseHover(object sender, EventArgs e)
        {
            Console.WriteLine(sender);
        }
    }
}
